[tool.black]
exclude = '''
/(
    \
  |
    \.eggs
  | \.git
  | \.mypy_cache
  | meta/migrations
  | docs
  | .venv
  | .pytest_cache
  | .snakemake
  | run-prebuilt-sector-coupled-euro-calliope
)/
'''
max-line-length=100

[tool.isort]
profile = "black"