name: jw4a-d2.1
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - flake8=3.8.3
    - snakemake-minimal=7.19.1
    - pre-commit
    - black
    - flake8
    - geopandas
    - cdsapi
    - pandas
    - netCDF4
    - ipykernel
    - atlite
    - pip
    - pip:
        - -e ./lib
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
