# The right place for all your configuration values.
slope: 4
x0: 5

data-sources:
    eez: "https://geo.vliz.be/geoserver/MarineRegions/wfs?service=WFS&version=1.0.0&request=GetFeature&typeNames=MarineRegions:eez&outputFormat=SHAPE-ZIP"

build_cutout:
    cutout_params:
        module: era5 # in priority order
        x: [-17., 37.]
        y: [32., 72.]
        dx: 0.3
        dy: 0.3
        # time: ['2014', '2014']

snapshots:
  start: "2014-01-01"
  end: "2015-01-01"
  inclusive: 'left'

scope:
    spatial:
        countries:
            - "Austria"
            - "Belgium"
            - "Bulgaria"
            - "Croatia"
            - "Cyprus"
            - "Czech Republic"
            - "Denmark"
            - "Estonia"
            - "Finland"
            - "France"
            - "Germany"
            - "Greece"
            - "Hungary"
            - "Ireland"
            - "Italy"
            - "Latvia"
            - "Lithuania"
            - "Luxembourg"
            - "Netherlands"
            - "Poland"
            - "Portugal"
            - "Romania"
            - "Slovakia"
            - "Slovenia"
            - "Spain"
            - "Sweden"
            - "United Kingdom"
            - "Albania"
            - "Bosnia and Herzegovina"
            - "Macedonia, Republic of"
            - "Montenegro"
            - "Norway"
            - "Serbia"
            - "Switzerland"
        bounds:
            x_min: -15.8
            x_max: 37
            y_min: 30
            y_max: 75


prepare_capacity_factors:
    onshore_awe:
        shapes: "data/europe-98-zones.geojson/europe-98-zones.geojson"
        cutout: "build/cutouts/cutout-era5-model-level_adapted_copy.nc"
        powercurve: "data/power_curves/AWE_500kw_softwing.csv"

    offshore_deep_awe:
        availability: "build/availability/availability_offshore_deep.nc"
        cutout: "build/cutouts/cutout-era5-model-level_adapted_copy.nc"
        powercurve: "data/power_curves/AWE_fixedwing1.csv"

    offshore_shallow_awe:
        availability: "build/availability/availability_offshore_shallow.nc"
        cutout: "build/cutouts/cutout-era5-model-level_adapted_copy.nc"
        powercurve: "data/power_curves/AWE_fixedwing1.csv"

    offshore_deep_hawt:
        availability: "build/availability/availability_offshore_deep.nc"
        cutout: ""  # TODO chose hawt cutout 
        powercurve: ""  # TODO Change to HAWT
        # offshore: 87 # m, median hub height of SWT-3.6-107 in Europe between 2010 and 2018
        # offshore: "siemens swt 3.6 107" # most built between 2010 and 2018 in Europe


draw_plots_capacityfactors:
    onshore_awe: "data/europe-98-zones.geojson/europe-98-zones.geojson"
    offshore_deep_awe: "build/shapes/eez.geojson"
    offshore_shallow_awe: "build/shapes/eez.geojson"
    offshore_deep_hawt: "build/shapes/eez.geojson"
